name: Compliance Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compliance:
    runs-on: self-hosted


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch full history so git diff works

      - name: Check system Python
        run: |
          python --version
          which python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml 

      - name: Run compliance checks
        run: python scripts/run_checks.py
