name: Check Naming Standards

on:
  pull_request:
    branches:
      - main

jobs:
  naming-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure origin/main is available
        shell: bash
        run: |
          git fetch origin main || true

      - name: Run naming standards check
        shell: bash
        run: |
          set -euo pipefail
          echo "🔎 Checking naming standards..."
          invalid=0

          changed=$(git diff --name-only origin/main...HEAD || true)
          if [[ -z "${changed// }" ]]; then
            echo "No changed files detected (diff is empty)."
            exit 0
          fi

          for file in $changed; do
            fname=$(basename "$file")

            # Notebook checks (.ipynb) -> nb_<3-letter-subdomain>_<desc>.ipynb
            if [[ "$fname" == *.ipynb ]]; then
              if [[ "$fname" =~ ^nb_([a-z]{3})_.+\.ipynb$ ]]; then
                sub=${BASH_REMATCH[1]}
                # this will always be 3 lowercase letters due to regex, so no need for length/digit check
              else
                echo "❌ Invalid notebook name: $file"
                echo "   - expected pattern: nb_<3-letter-subdomain>_<description>.ipynb (e.g. nb_fin_sales.ipynb)"
                invalid=1
              fi

            # Job checks (.py, .yml, .yaml) -> jb_<3-letter-subdomain>_<desc>.(py|yml|yaml)
            elif [[ "$fname" == *.yml || "$fname" == *.yaml ]]; then
              if [[ "$fname" =~ ^jb_([a-z]{3})_.+\.(py|yml|yaml)$ ]]; then
                sub=${BASH_REMATCH[1]}
              else
                echo "❌ Invalid job name: $file"
                echo "   - expected pattern: jb_<3-letter-subdomain>_<description>.(py|yml|yaml) (e.g. jb_hrm_load.yml)"
                invalid=1
              fi
            fi